development:
  sessions:
    default:
      database: mtg_pack_generator_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: mtg_pack_generator_test
      hosts:
        - localhost:27017

# set these environment variables on your prod server
production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
